name: flutter_core_spotlight
description: Flutter plugin used for indexing items in Spotlight search on iOS.
version: 1.0.4
homepage: https://github.com/mattcianna/flutter_core_spotlight
repository: https://github.com/mattcianna/flutter_core_spotlight

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterCoreSpotlightPlugin